---
- name: Export Satellite Configuration 
  hosts: localhost
  gather_facts: false
  vars_files:
    - vars/test_vars.yml
  tasks:
    - block:
      - name: Get Organizations
        include_tasks: tasks/get_organizations.yml
      tags:
        - 'organizations'

    - block:
      - name: Get Locations
        include_tasks: tasks/get_locations.yml
      tags:
        - 'locations'

    - block:
      - name: Get Domains
        include_tasks: tasks/get_domains.yml
      tags:
        - 'domains'

    - block:
      - name: Get Subnets
        include_tasks: tasks/get_subnets.yml
      tags:
        - 'subnets'

    - block:
      - name: Get Repositories
        include_tasks: tasks/get_repositories.yml
      tags:
        - 'repositories'

    - block:
      - name: Get Repositories
        include_tasks: tasks/get_repository_sets.yml
      tags:
        - 'repository_sets'

    - block:
      - name: Get Host Groups
        include_tasks: tasks/get_hostgroups.yml
      tags:
        - 'hostgroups'

    - block:
      - name: Get Operating Systems
        include_tasks: tasks/get_operatingsystems.yml
      tags:
        - 'operatingsystems'

    - block:
      - name: Get Lifecycle Environments
        include_tasks: tasks/get_lifecycle_environments.yml
      tags:
        - 'lifecycle_environments'

    - block:
      - name: Get Content Views
        include_tasks: tasks/get_content_views.yml
      tags:
        - 'content_views'

    - block:
      - name: Get Composite Content Views
        include_tasks: tasks/get_composite_content_views.yml
      tags:
        - 'composite_content_views'

    - block:
      - name: Get Content View Filters
        include_tasks: tasks/get_content_view_filters.yml
      tags:
        - 'content_view_filters'

    - block:
      - name: Get Custom Products
        include_tasks: tasks/get_products.yml
      tags:
        - 'products'

    - block:
      - name: Get Settings
        include_tasks: tasks/get_settings.yml
      tags:
        - 'settings'

    - block:
      - name: Get Content Credentials
        include_tasks: tasks/get_content_credentials.yml
      tags:
        - 'content_credentials'


