---
- name: "{{ call_type }} | API call - {{ api_link }}"
  ansible.builtin.uri:
    url: "{{ test.satellite.server_url }}{{ api_link }}"
    method: GET
    user: "{{ test.satellite.admin.username }}"
    password: "{{ test.satellite.admin.password }}"
    force_basic_auth: true
    validate_certs: false
    return_content: true
    body_format: "{{ body_format | default(omit) }}"
    body: "{{ body | default(omit) }}"
    timeout: 1200
  register: __result_api_response

- name: "{{ call_type }} | API call - merge results 1/2"
  ansible.builtin.set_fact:
    __result_api_response_results: "{{ (result_api_response.json.results | default([])) + (__result_api_response.json.results | default([])) }}"

- name: "{{ call_type }} | API call - merge results 2/2"
  ansible.builtin.set_fact:
    result_api_response: "{{ __result_api_response | combine({'json': {'results': __result_api_response_results}}) }}"
...
