---
- name: Content View Filters | Get Info
  include_tasks: api_call.yml
  vars:
    call_type: Content View Filters
    api_link: /katello/api/content_view_filters

- name: Content View Filters | Create a List
  ansible.builtin.set_fact:
    info_list: "{{ result_api_response.json.results | sort(attribute='id') | unique  }}"

- name: Content View Filters | Get Detailed Info
  include_tasks: detailed_api_call.yml
  vars:
    call_type: Content View Filters
    api_link: /katello/api/content_view_filters/
    loop_var: "{{ all_results }}"

- name: Content View Filters | Template Out Results
  include_tasks: template_out.yml
  vars:
    template_type: content_view_filters

