---
- name: Repositories | Get Basic Info
  include_tasks: api_call.yml
  vars:
    call_type: Repositories
    api_link: /katello/api/repositories?full_result=true

- name: Repositories | Create a List
  ansible.builtin.set_fact:
    all_results: "{{ result_api_response.json.results | sort(attribute='id') | rejectattr('product.orphaned','==',true) }}"     

- name: Repositories | Get Detailed Info
  include_tasks: detailed_api_call.yml
  vars:
    call_type: Repositories
    api_link: /katello/api/repositories/
    loop_var: "{{ all_results }}"

- name: Repositories | Template Out Results 
  include_tasks: template_out.yml
  vars:
    template_type: repositories
