---
- name: Domains | Get Basic Info
  include_tasks: api_call.yml
  vars:
    call_type: Domains
    api_link: /api/domains?per_page=all

- name: Domains | Create a List
  ansible.builtin.set_fact:
    all_results: "{{ result_api_response.json.results | sort(attribute='id')  }}"     

- name: Domains | Get Detailed Info
  include_tasks: detailed_api_call.yml
  vars:
    call_type: Domains
    api_link: /api/domains/
    loop_var: "{{ all_results }}"

- name: Domains | Template Out Results
  include_tasks: template_out.yml
  vars:
    template_type: domains
