---
- name: Organizations | Get Info
  redhat.satellite.organization_info:
    server_url: "{{ test.satellite.server_url }}"
    username: "{{ test.satellite.admin.username }}"
    password: "{{ test.satellite.admin.password }}"
    validate_certs: "{{ test.satellite.validate_tls_certs_of_foreman_server_boolean }}"
  register: result_api_response

- name: Organizations | Set Info List
  ansible.builtin.set_fact:
    info_list: "{{ result_api_response.organizations }}" # removed filter | rejectattr('name','==', 'Default Organization')

- name: Organizations | Template Out Results
  include_tasks: template_out.yml
  vars:
    template_type: organizations
