---
- name: Content View Filters | Get Info
  include_tasks: api_call.yml
  vars:
    call_type: Content View Filters
    api_link: /katello/api/content_view_filters

- name: Content View Filters | Set Info List
  ansible.builtin.set_fact:
    info_list: "{{ result_api_response.json.results }}"

- name: Content View Filters | Debug
  ansible.builtin.debug:
    msg: "{{ info_list }}"

- name: Content View Fitlers | Debug specific var
  ansible.builtin.debug:
    msg: |
      {% for i in info_list %}
      "{{ i.name }}"
      {% endfor %}

- name: Content View Filters | Template Out Results
  include_tasks: template_out.yml
  vars:
    template_type: content_view_filters
