---
- name: Host Groups | Get Basic Info
  include_tasks: api_call.yml
  vars:
    call_type: Host Groups
    api_link: /api/hostgroups

- name: Host Groups | Create a List
  ansible.builtin.set_fact:
    all_results: "{{ result_api_response.json.results }}"     

- name: Host Groups | Get Detailed Info
  include_tasks: detailed_api_call.yml
  vars:
    call_type: Host Groups 
    api_link: /api/hostgroups/
    loop_var: "{{ all_results }}"

- name: Host Groups | Template Out Results 
  include_tasks: template_out.yml
  vars:
    template_type: hostgroups
