---
- name: Domains | Get Info
  redhat.satellite.domain_info:
    server_url: "{{ test.satellite.server_url }}"
    username: "{{ test.satellite.admin.username }}"
    password: "{{ test.satellite.admin.password }}"
    validate_certs: "{{ test.satellite.validate_tls_certs_of_foreman_server_boolean }}"
  register: __domain_result_api_response

- name: Domains | Set Info List
  ansible.builtin.set_fact:
    info_list: "{{ __domain_result_api_response.domains | sort(attribute='id') }}" # removed filter | rejectattr('name','==', 'Default Organization')

- name:
  debug:
    msg: "{{ info_list }}"  

- name: Domains | Template Out Results
  include_tasks: template_out.yml
  vars:
    template_type: domains
