---
- name: Subnets | Get Basic Info
  include_tasks: api_call.yml
  vars:
    call_type: Subnets
    api_link: /api/subnets?full_result=true

- name: Subnets | Create a List
  ansible.builtin.set_fact:
    all_results: "{{ result_api_response.json.results | sort(attribute='id') }}"     

- name: Subnets | Get Detailed Info
  include_tasks: detailed_api_call.yml
  vars:
    call_type: Subnets
    api_link: /api/subnets/
    loop_var: "{{ all_results }}"

- name: Subnets | Template Out Results
  include_tasks: template_out.yml
  vars:
    template_type: subnets
