---
- name: Get Lifecycle Environments 
  hosts: localhost
  gather_facts: false
  vars_files:
    - vars/vars.yml
  tasks:
    - name: Lifecycle Environments | Get Basic Info
      ansible.builtin.uri:
        url: "{{ satellite_url }}/katello/api/environments"
        method: GET
        user: "{{ satellite_username }}"
        password: "{{ satellite_passwd }}"
        force_basic_auth: true
        validate_certs: false
        return_content: true
      register: result_api_response

    - name: Lifecycle Environments | Set Info List
      ansible.builtin.set_fact:
        lifecycle_envs_info_list: "{{ result_api_response.json.results | rejectattr('name','==', 'Library') }}"

    - name: Lifecycle Environments | Template Out Results
      ansible.builtin.template:
        src: templates/lifecycle_environments.yml.j2
        dest: configs/lifecycle_environments.yml
        owner: "{{ template_owner }}"
        group: "{{ template_group }}"
        mode: "{{ template_mode }}"
