---
- name: Settings | Get Basic Info
  redhat.satellite.setting_info:
    server_url: "{{ satellite.server_url }}"
    username: "{{ satellite.admin.username }}"
    password: "{{ satellite.admin.password }}"
    validate_certs: "{{ satellite.validate_tls_certs_of_foreman_server_boolean }}"
  register: __setting_result_api_response

- name: Settings | Set Info List
  ansible.builtin.set_fact:
    info_list: "{{ __setting_result_api_response.settings | sort(attribute='id') }}"

- name:
  debug:
    msg: "{{ info_list }}"

- name: Settings | Template Out Results
  include_tasks: template_out.yml
  vars:
    template_type: settings
...
