---
# defaults file for dispatch
- name: Manage Satellite Settings
  include_tasks: satellite_settings.yaml
  args:
    apply:
      tags: satellite_settings
  tags: satellite_settings

- name: Manage LDAP Authentication
  include_tasks: satellite_auth_sources_ldap.yaml
  args:
    apply:
      tags: satellite_auth_sources_ldap
  tags: satellite_auth_sources_ldap

- name: Manage User Groups
  include_tasks: satellite_usergroups.yaml
  args:
    apply:
      tags: satellite_usergroups
  tags: satellite_usergroups

- name: Create Organizations
  include_tasks: satellite_organizations.yaml
  args:
    apply:
      tags: satellite_organizations
  tags: satellite_organizations

- name: Manage Locations
  include_tasks: satellite_locations.yaml
  args:
    apply:
      tags: satellite_locations
  tags: satellite_locations

- name: Manage Lifecycle Environments
  include_tasks: satellite_lifecycle_environments.yaml
  args:
    apply:
      tags: satellite_lifecycle_environments
  tags: satellite_lifecycle_environments

- name: Manage Repository Sets
  include_tasks: satellite_repository_sets.yaml
  args:
    apply:
      tags: satellite_repository_sets
  tags: satellite_repository_sets

- name: Manage Repositories
  include_tasks: satellite_repositories.yaml
  args:
    apply:
      tags: satellite_repositories
  tags: satellite_repositories

- name: Manage Sync Plans
  include_tasks: satellite_sync_plans.yaml
  args:
    apply:
      tags: satellite_sync_plans
  tags: satellite_sync_plans

- name: Manage Content Views
  include_tasks: satellite_content_views.yaml
  args:
    apply:
      tags: satellite_content_views
  tags: satellite_content_views

# Don't treat this appart from Content Views by now
# - name: Manage Content Views Filters
#   include_tasks: satellite_content_view_filters.yaml
#   args:
#     apply:
#       tags: satellite_content_view_filters
#   tags: satellite_content_view_filters
# Don't treat this appart from Content Views by now

- name: Publish and Promote Content Views
  when: false
  include_tasks: satellite_cv_versions.yaml
  args:
    apply:
      tags: satellite_cv_publish_promote
  tags: satellite_cv_publish_promote

- name: Manage Activation Keys
  include_tasks: satellite_activation_keys.yaml
  args:
    apply:
      tags: satellite_activation_keys
  tags: satellite_activation_keys

- name: Manage Host Collections
  include_tasks: satellite_host_collections.yaml
  args:
    apply:
      tags: satellite_host_collections
  tags: satellite_host_collections

- name: Create Products
  include_tasks: satellite_products.yaml
  args:
    apply:
      tags: satellite_products
  tags: satellite_products

- name: Create Content Credentials
  include_tasks: satellite_content_credentials.yaml
  args:
    apply:
      tags: satellite_content_credentials
  tags: satellite_content_credentials

- name: Create Partition Tables
  include_tasks: satellite_partition_tables.yaml
  args:
    apply:
      tags: satellite_partition_tables
  tags: satellite_partition_tables

- name: Create Provisioning Templates
  include_tasks: satellite_provisioning_templates.yaml
  args:
    apply:
      tags: satellite_provisioning_templates
  tags: satellite_provisioning_templates

- name: Create OperatingSystems
  include_tasks: satellite_operatingsystems.yaml
  args:
    apply:
      tags: satellite_operatingsystems
  tags: satellite_operatingsystems
...
