---
- name: Create Content Views
  ansible.builtin.import_role:
    name: redhat.satellite.content_views
  vars:
    satellite_username: "{{ username }}"
    satellite_password: "{{ password }}"
    satellite_server_url: "{{ server_url }}"
    satellite_validate_certs: "{{ validate_certs }}"
...
