---
- name: "{{ call_type }} | API call - {{ api_link }}"
  ansible.builtin.uri:
    url: "{{ satellite.server_url }}{{ api_link }}{{ item.id }}"
    method: GET
    user: "{{ satellite.admin.username }}"
    password: "{{ satellite.admin.password }}"
    force_basic_auth: true
    validate_certs: false
    return_content: true
    body_format: "{{ body_format | default(omit) }}"
    body: "{{ body | default(omit) }}"
    timeout: 1200
  loop: "{{ loop_var }}"
  register: detailed_info
