---
- name: Repository Sets (Do Work) | Get Info
  include_tasks: api_call.yaml
  vars:
    call_type: Repository Sets
    api_link: "/katello/api/repository_sets?organization_id={{ __current_org.id }}&full_result=true"

- name: Repository Sets (Do Work) | Block to do the job when there's a job to do
  when:
    - result_api_response.json.results is defined
    - result_api_response.json.results | length > 0
  block:
    - name: Repository Sets (Do Work) | Set Info List (can take a while...)
      ansible.builtin.set_fact:
        __rs_info_list:
          organization: "{{ __current_org.name }}"
          info_list: "{{ result_api_response.json.results }}"
...
