---
- name: Operating Systems | Reset the results variable
  ansible.builtin.set_fact:
    result_api_response: {}
    __rs_info_list: []

- name: Operating Systems | Get Operating Systems
  include_tasks: api_call.yaml
  vars:
    call_type: Operating Systems
    api_link: "/api/operatingsystems?per_page=all"

- name: Operating Systems | Retain the Operating Systems' info
  ansible.builtin.set_fact:
    __operatingsystems_list: "{{ result_api_response.json.results }}"

- name: Operating Systems | Get External Operating Systems Info
  include_tasks: get_operatingsystems_do_work.yaml
  loop: "{{ __operatingsystems_list }}"
  loop_control:
    loop_var: __current_operatingsystem

- name: Operating Systems | Template Out Results
  include_tasks: template_out.yaml
  vars:
    template_type: satellite_operatingsystems
    info_list: "{{ __rs_info_list | default([]) }}"
...
