---
- name: Subnets | Get Info
  redhat.satellite.subnet_info:
    server_url: "{{ satellite.server_url }}"
    username: "{{ satellite.admin.username }}"
    password: "{{ satellite.admin.password }}"
    validate_certs: "{{ satellite.validate_certs }}"
  register: __subnets_result_api_response

- name: Subnets | Create a List
  ansible.builtin.set_fact:
    info_list: "{{ __subnets_result_api_response.subnets | sort(attribute='id') }}"

- name: Subnets | Template Out Results
  include_tasks: template_out.yaml
  vars:
    template_type: satellite_subnets
...
