---
- name: Repository Sets | Reset the results variable
  ansible.builtin.set_fact:
    result_api_response: {}

- name: Repository Sets | Get Basic Info
  include_tasks: api_call.yml
  vars:
    call_type: Repository Sets
    api_link: /katello/api/repository_sets?enabled=true&organization_id=1&full_result=true

- name: Repository Sets | Create a List
  ansible.builtin.set_fact:
    all_results: "{{ result_api_response.json.results | sort(attribute='id') }}"

- name: Repository Sets | Get Detailed Info
  include_tasks: detailed_api_call.yml
  vars:
    call_type: Repository Sets
    api_link: /katello/api/repository_sets/
    body_format: "json"
    body: "{\"organization_id\":1}"
    loop_var: "{{ all_results }}"

- name: Repository Sets | Template Out Results
  include_tasks: template_out.yml
  vars:
    template_type: satellite_repository_sets
