---
- name: Settings | Get Basic Info
  redhat.satellite.setting_info:
    server_url: "{{ satellite.server_url }}"
    username: "{{ satellite.admin.username }}"
    password: "{{ satellite.admin.password }}"
    validate_certs: "{{ satellite.validate_certs }}"
  register: __setting_result_api_response

- name: Settings | Set Info List
  ansible.builtin.set_fact:
    info_list: "{{ __setting_result_api_response.settings | sort(attribute='id') }}"

- name: Settings | Template Out Results
  include_tasks: template_out.yaml
  vars:
    template_type: satellite_settings
...
