---
- name: Host Collections | Reset the results variable
  ansible.builtin.set_fact:
    result_api_response: {}

- name: Host Collections | Get Info
  include_tasks: api_call.yaml
  vars:
    call_type: Host Collections
    api_link: /katello/api/host_collections?full_result=true

- name: Host Collections | Set Info List
  ansible.builtin.set_fact:
    info_list: "{{ result_api_response.json.results | sort(attribute='id') }}"

- name: Host Collections | Template Out Results
  include_tasks: template_out.yaml
  vars:
    template_type: satellite_host_collections
...

