---
- block:
  - name: Get Organizations
    include_tasks: get_organizations.yaml
  tags:
    - 'organizations'

- block:
  - name: Get Locations
    include_tasks: get_locations.yaml
  tags:
    - 'locations'

- block:
  - name: Get Domains
    include_tasks: get_domains.yaml
  tags:
    - 'domains'

- block:
  - name: Get Subnets
    include_tasks: get_subnets.yaml
  tags:
    - 'subnets'

- block:
  - name: Get Repositories
    include_tasks: get_repositories.yaml
  tags:
    - 'repositories'

- block:
  - name: Get Repositories
    include_tasks: get_repository_sets.yaml
  tags:
    - 'repository_sets'

- block:
  - name: Get Host Groups
    include_tasks: get_hostgroups.yaml
  tags:
    - 'hostgroups'

- block:
  - name: Get Operating Systems
    include_tasks: get_operatingsystems.yaml
  tags:
    - 'operatingsystems'

- block:
  - name: Get Lifecycle Environments
    include_tasks: get_lifecycle_environments.yaml
  tags:
    - 'lifecycle_environments'

- block:
  - name: Get Content Views
    include_tasks: get_content_views.yaml
  tags:
    - 'content_views'

- block:
  - name: Get Custom Products
    include_tasks: get_products.yaml
  tags:
    - 'products'

- block:
  - name: Get Settings
    include_tasks: get_settings.yaml
  tags:
    - 'settings'

- block:
  - name: Get Content Credentials
    include_tasks: get_content_credentials.yaml
  tags:
    - 'content_credentials'

- block:
  - name: Get Activation Keys
    include_tasks: get_activation_keys.yaml
  tags:
    - 'activation_keys'

- block:
  - name: Get Sync Plans
    include_tasks: get_sync_plans.yaml
  tags:
    - 'sync_plans'

- block:
  - name: Get Auth Sources LDAP
    include_tasks: get_auth_sources_ldap.yaml
  tags:
    - 'auth_sources_ldap'

- block:
  - name: Get Host Collections
    include_tasks: get_host_collections.yaml
  tags:
    - 'host_collections'

- block:
  - name: Get External Usergroups
    include_tasks: get_usergroups.yaml
  tags:
    - 'usergroups'
...
