---
composite_content_views:
  - name: "CompositeContentView"
    label: "CompositeContentView"
    auto_publish: "False"
    organization: "Primary Organization"
    components:
      - content_view: "PrimaryHA"
        latest: "True"
      - content_view: "PrimaryServerBase"
        latest: "True"
  - name: "Composite Base Custom"
    label: "Composite_Base_Custom"
    auto_publish: "False"
    organization: "Primary Organization"
    components:
      - content_view: "Custom Software Content View"
        latest: "True"
      - content_view: "PrimaryServerBase"
        latest: "True"
  - name: "test"
    label: "test"
    auto_publish: "False"
    organization: "Primary Organization"
