---
content_views:
  - name: "Boston HA Project"
    label: "Boston_HA_Project"
    description: "HA packages for Boston project"
    organization: "Operations"
    repositories:
      - name: "Red Hat Enterprise Linux 9 for x86_64 - AppStream RPMs 9"
        product: "Red Hat Enterprise Linux for x86_64"
      - name: "Red Hat Enterprise Linux 9 for x86_64 - BaseOS RPMs 9"
        product: "Red Hat Enterprise Linux for x86_64"
      - name: "Red Hat Enterprise Linux 9 for x86_64 - High Availability RPMs 9"
        product: "Red Hat Enterprise Linux High Availability for x86_64"
  - name: "FinanceServerBase"
    label: "FinanceServerBase"
    description: ""
    organization: "Finance"
    repositories:
      - name: "Red Hat Enterprise Linux 9 for x86_64 - BaseOS RPMs 9"
        product: "Red Hat Enterprise Linux for x86_64"
      - name: "Red Hat Enterprise Linux 9 for x86_64 - AppStream RPMs 9"
        product: "Red Hat Enterprise Linux for x86_64"
      - name: "Red Hat Satellite Client 6 for RHEL 9 x86_64 RPMs"
        product: "Red Hat Enterprise Linux for x86_64"
  - name: "FinBaseHA"
    label: "FinBaseHA"
    description: ""
    organization: "Finance"
    repositories:
      - name: "Red Hat Enterprise Linux 9 for x86_64 - High Availability RPMs 9"
        product: "Red Hat Enterprise Linux High Availability for x86_64"
  - name: "MarketingServerBase"
    label: "MarketingServerBase"
    description: "Base Packages"
    organization: "Marketing"
    repositories:
      - name: "Red Hat Enterprise Linux 9 for x86_64 - BaseOS RPMs 9"
        product: "Red Hat Enterprise Linux for x86_64"
      - name: "Red Hat Enterprise Linux 9 for x86_64 - AppStream RPMs 9"
        product: "Red Hat Enterprise Linux for x86_64"
      - name: "Red Hat Satellite Client 6 for RHEL 9 x86_64 RPMs"
        product: "Red Hat Enterprise Linux for x86_64"
  - name: "OperationsServerBase"
    label: "OperationsServerBase"
    description: "Base Packages"
    organization: "Operations"
    repositories:
      - name: "Red Hat Enterprise Linux 9 for x86_64 - BaseOS RPMs 9"
        product: "Red Hat Enterprise Linux for x86_64"
      - name: "Red Hat Enterprise Linux 9 for x86_64 - AppStream RPMs 9"
        product: "Red Hat Enterprise Linux for x86_64"
      - name: "Red Hat Satellite Client 6 for RHEL 9 x86_64 RPMs"
        product: "Red Hat Enterprise Linux for x86_64"
      - name: "Admin Tools"
        product: "Custom Software"
