---
content_views:
  - name: "Default Organization View"
    label: "Default_Organization_View"
    description: ""
    organization: "Primary Organization"
    repositories:
  - name: "Default Organization View"
    label: "Default_Organization_View"
    description: ""
    organization: "Operations"
    repositories:
  - name: "PrimaryServerBase"
    label: "PrimaryServerBase"
    description: ""
    organization: "Primary Organization"
    repositories:
      - name: "Red Hat Enterprise Linux 8 for x86_64 - AppStream RPMs 8"
        product: "Red Hat Enterprise Linux for x86_64"
      - name: "Red Hat Enterprise Linux 8 for x86_64 - BaseOS RPMs 8"
        product: "Red Hat Enterprise Linux for x86_64"
      - name: "Red Hat Enterprise Linux 8 for x86_64 - AppStream Kickstart 8.10"
        product: "Red Hat Enterprise Linux for x86_64"
      - name: "Red Hat Enterprise Linux 8 for x86_64 - BaseOS Kickstart 8.10"
        product: "Red Hat Enterprise Linux for x86_64"
  - name: "PrimaryHA"
    label: "PrimaryHA"
    description: "Excluding Pacemaker packages earlier than 2.1.4"
    organization: "Primary Organization"
    repositories:
      - name: "Red Hat Enterprise Linux 8 for x86_64 - High Availability RPMs 8"
        product: "Red Hat Enterprise Linux High Availability for x86_64"
  - name: "Custom Software Content View"
    label: "Custom_Software_Content_View"
    description: ""
    organization: "Primary Organization"
    repositories:
      - name: "Admin Tools"
        product: "Custom Software"
