---
domains:
  - name: "boston.lab.eiva.com"
    description: ""
    organizations:
      - "Operations"
      - "Primary Organization"
    locations:
      - "Boston"
      - "Boston/Boston East"
      - "Boston/Boston West"
      - "Default Location"
  - name: "lab.eiva.com"
    description: "Primary domain"
    organizations:
      - "Operations"
      - "Primary Organization"
    locations:
      - "Boston"
      - "Boston/Boston East"
      - "Boston/Boston West"
      - "Default Location"
  - name: "lab.example.com"
    description: "Example lab domain"
    organizations:
      - "Operations"
      - "Primary Organization"
    locations:
      - "Boston"
      - "Boston/Boston East"
      - "Boston/Boston West"
      - "Default Location"
  - name: "prod.domain.local"
    description: "Production Domain for Local Network"
    organizations:
      - "Operations"
    locations:
      - "Boston"
      - "Boston/Boston East"
  - name: "test.domain.local"
    description: "Test Domain for Local Networks"
    organizations:
      - "Operations"
    locations:
      - "Boston"
      - "Boston/Boston East"
      - "Boston/Boston West"
      - "Default Location"
