---
hostgroups:
  - name: "Host Group 1"
    parameters:
      - name: "h_group_param1"
        parameter_type: "integer"
        value: "1"
      - name: "h_group_param2"
        parameter_type: "string"
        value: "Test"
  - name: "Host Group 2"
    description: "Description for the host group 2"
    parent: "Host Group 1"
    parameters:
      - name: "h_group_param3"
        parameter_type: "string"
        value: "Test2"
  - name: "Main Host Group (Parent)"
    description: "This is a main host group"
    parameters:
      - name: "kt_activation_keys"
        parameter_type: "string"
        value: "Build-CompositeContentView"
      - name: "test1"
        parameter_type: "string"
        value: "test_string_1"
      - name: "test2"
        parameter_type: "integer"
        value: "123"
  - name: "Main Host Group (Child)"
    description: "This a child test host group"
    parent: "Main Host Group (Parent)"
    parameters:
      - name: "kt_activation_keys"
        parameter_type: "string"
        value: "Build-CompositeContentView"
      - name: "test1"
        parameter_type: "string"
        value: "child_test_string_1"
      - name: "test2"
        parameter_type: "integer"
        value: "555"
      - name: "test3"
        parameter_type: "string"
        value: "Child only test string"
  - name: "New Group"
    description: "New Group without parameters"
