---
lifecycle_environments:
  - name: "Build"
    label: "Build"
    prior: "Library"
  - name: "Development"
    label: "Development"
    prior: "Library"
  - name: "QA"
    label: "QA"
    prior: "Development"
  - name: "Test"
    label: "Test"
    prior: "Build"
  - name: "Deploy"
    label: "Deploy"
    prior: "Test"
  - name: "Production"
    label: "Production"
    prior: "QA"
