---
locations:
- name: "Boston"
  description: ""
  parent: ""
- name: "Boston East"
  description: "This is a Boston East location"
  parent: "Boston"
- name: "Boston West"
  description: ""
  parent: "Boston"
