---
locations:
  - name: "Boston"
    description: ""
    parent: ""
  - name: "Boston East"
    description: ""
    parent: "Boston"
  - name: "Boston West"
    description: ""
    parent: "Boston"
  - name: "Default Location"
    description: ""
    parent: ""
