---
operatingsystems:
  - name: "RedHat"
    description: "RHEL 8.10"
    os_family: "Redhat"
    major: "8"
    password_hash: "SHA256"
    state: present
    architectures:
      - "x86_64"
    ptables:
      - "Kickstart default"
