---
# Set the primary organization manually
# primary_organization: ORGANIZATION_NAME

organizations:
  - name: "Finance"
    label: "Finance"
    description: ""
  - name: "Marketing"
    label: "Marketing"
    description: "Marketing Department"
  - name: "Operations"
    label: "Operations"
    description: ""

all_organizations:
  - "Finance"
  - "Marketing"
  - "Operations"

