---
primary_organization: "Umbrella" 

organizations:
  - name: "Umbrella"
    label: "Umbrella"
    description: ""
  - name: "red_ribbon"
    label: "Red_Ribbon"
    description: ""
  - name: "red_ribbon_new"
    label: "red_ribbon_new"
    description: ""
  - name: "red_ribbon_new_demo"
    label: "red_ribbon_new_demo"
    description: ""

all_organizations:
  - "Umbrella"
  - "red_ribbon"
  - "red_ribbon_new"
  - "red_ribbon_new_demo"

