---
primary_organization: "Umbrella" 

organizations:
  - name: "Umbrella"
    label: "Umbrella"
    description: ""
  - name: "Red_Ribbon"
    label: "Red_Ribbon"
    description: ""

all_organizations:
  - "Umbrella"
  - "Red_Ribbon"

