---
repositories:
  - name: "Red Hat Enterprise Linux 8 for x86_64 - BaseOS RPMs 8"
    label: "Red_Hat_Enterprise_Linux_8_for_x86_64_-_BaseOS_RPMs_8"
    url: "https://cdn.********.com/content/dist/rhel8/8/x86_64/baseos/os"
    http_proxy_policy: "global_default_http_proxy"
    content_type: "yum"
    product: "Red Hat Enterprise Linux for x86_64"
    redhat: "True"
    mirroring_policy: "mirror_complete"
    download_policy: "on_demand"
  - name: "Red Hat Enterprise Linux 8 for x86_64 - AppStream RPMs 8"
    label: "Red_Hat_Enterprise_Linux_8_for_x86_64_-_AppStream_RPMs_8"
    url: "https://cdn.********.com/content/dist/rhel8/8/x86_64/appstream/os"
    http_proxy_policy: "global_default_http_proxy"
    content_type: "yum"
    product: "Red Hat Enterprise Linux for x86_64"
    redhat: "True"
    mirroring_policy: "mirror_complete"
    download_policy: "on_demand"
  - name: "Red Hat Enterprise Linux 8 for x86_64 - BaseOS Kickstart 8.10"
    label: "Red_Hat_Enterprise_Linux_8_for_x86_64_-_BaseOS_Kickstart_8_10"
    url: "https://cdn.********.com/content/dist/rhel8/8.10/x86_64/baseos/kickstart"
    http_proxy_policy: "global_default_http_proxy"
    content_type: "yum"
    product: "Red Hat Enterprise Linux for x86_64"
    redhat: "True"
    mirroring_policy: "mirror_complete"
    download_policy: "immediate"
  - name: "Red Hat Enterprise Linux 8 for x86_64 - AppStream Kickstart 8.10"
    label: "Red_Hat_Enterprise_Linux_8_for_x86_64_-_AppStream_Kickstart_8_10"
    url: "https://cdn.********.com/content/dist/rhel8/8.10/x86_64/appstream/kickstart"
    http_proxy_policy: "global_default_http_proxy"
    content_type: "yum"
    product: "Red Hat Enterprise Linux for x86_64"
    redhat: "True"
    mirroring_policy: "mirror_complete"
    download_policy: "immediate"
  - name: "Red Hat Enterprise Linux 8 for x86_64 - High Availability RPMs 8"
    label: "Red_Hat_Enterprise_Linux_8_for_x86_64_-_High_Availability_RPMs_8"
    url: "https://cdn.********.com/content/dist/rhel8/8/x86_64/highavailability/os"
    http_proxy_policy: "global_default_http_proxy"
    content_type: "yum"
    product: "Red Hat Enterprise Linux High Availability for x86_64"
    redhat: "True"
    mirroring_policy: "mirror_complete"
    download_policy: "on_demand"
  - name: "Admin Tools"
    label: "Admin_Tools"
    url: "https://devsatellite.lab.eiva.com/pulp/content/Primary_Organization/Library/custom/Custom_Software/Admin_Tools/"
    http_proxy_policy: "none"
    content_type: "yum"
    product: "Custom Software"
    redhat: "False"
    mirroring_policy: "mirror_content_only"
    download_policy: "on_demand"
    gpg_key: "Example Software"
  - name: "New Custom Repository"
    label: "New_Custom_Repository"
    description: "This is a new custom repo: included sm software"
    url: "https://custom.url/"
    http_proxy_policy: "global_default_http_proxy"
    content_type: "yum"
    product: "New Custom Product"
    redhat: "False"
    mirroring_policy: "mirror_content_only"
    download_policy: "immediate"
    gpg_key: "SM Software"
  - name: "Red Hat Satellite Capsule 6.11 for RHEL 8 x86_64 RPMs"
    label: "Red_Hat_Satellite_Capsule_6_11_for_RHEL_8_x86_64_RPMs"
    url: "https://cdn.********.com/content/dist/layered/rhel8/x86_64/sat-capsule/6.11/os"
    http_proxy_policy: "global_default_http_proxy"
    content_type: "yum"
    product: "Red Hat Satellite Capsule"
    redhat: "True"
    mirroring_policy: "mirror_complete"
    download_policy: "on_demand"
  - name: "Red Hat Satellite Client 6 for RHEL 8 x86_64 RPMs"
    label: "Red_Hat_Satellite_Client_6_for_RHEL_8_x86_64_RPMs"
    url: "https://cdn.********.com/content/dist/layered/rhel8/x86_64/sat-client/6/os"
    http_proxy_policy: "global_default_http_proxy"
    content_type: "yum"
    product: "Red Hat Enterprise Linux for x86_64"
    redhat: "True"
    mirroring_policy: "mirror_complete"
    download_policy: "on_demand"
  - name: "Red Hat Satellite Maintenance 6.11 for RHEL 8 x86_64 RPMs"
    label: "Red_Hat_Satellite_Maintenance_6_11_for_RHEL_8_x86_64_RPMs"
    url: "https://cdn.********.com/content/dist/layered/rhel8/x86_64/sat-maintenance/6.11/os"
    http_proxy_policy: "global_default_http_proxy"
    content_type: "yum"
    product: "Red Hat Enterprise Linux for x86_64"
    redhat: "True"
    mirroring_policy: "mirror_complete"
    download_policy: "on_demand"
  - name: "Red Hat Satellite Capsule 6.16 for RHEL 8 x86_64 RPMs"
    label: "Red_Hat_Satellite_Capsule_6_16_for_RHEL_8_x86_64_RPMs"
    url: "https://cdn.********.com/content/dist/layered/rhel8/x86_64/sat-capsule/6.16/os"
    http_proxy_policy: "global_default_http_proxy"
    content_type: "yum"
    product: "Red Hat Satellite Capsule"
    redhat: "True"
    mirroring_policy: "mirror_complete"
    download_policy: "on_demand"
  - name: "Red Hat Satellite Maintenance 6.16 for RHEL 8 x86_64 RPMs"
    label: "Red_Hat_Satellite_Maintenance_6_16_for_RHEL_8_x86_64_RPMs"
    url: "https://cdn.********.com/content/dist/layered/rhel8/x86_64/sat-maintenance/6.16/os"
    http_proxy_policy: "global_default_http_proxy"
    content_type: "yum"
    product: "Red Hat Enterprise Linux for x86_64"
    redhat: "True"
    mirroring_policy: "mirror_complete"
    download_policy: "on_demand"
  - name: "Red Hat Enterprise Linux High Availability for RHEL 7 Server RPMs x86_64 7Server"
    label: "Red_Hat_Enterprise_Linux_High_Availability_for_RHEL_7_Server_RPMs_x86_64_7Server"
    url: "https://cdn.********.com/content/dist/rhel/server/7/7Server/x86_64/highavailability/os"
    http_proxy_policy: "global_default_http_proxy"
    content_type: "yum"
    product: "Red Hat Enterprise Linux High Availability for x86_64"
    redhat: "True"
    mirroring_policy: "mirror_complete"
    download_policy: "on_demand"
  - name: "Red Hat Enterprise Linux 6 Server - Extended Update Support RPMs x86_64 6.5"
    label: "Red_Hat_Enterprise_Linux_6_Server_-_Extended_Update_Support_RPMs_x86_64_6_5"
    url: "https://cdn.********.com/content/eus/rhel/server/6/6.5/x86_64/os"
    http_proxy_policy: "global_default_http_proxy"
    content_type: "yum"
    product: "Red Hat Enterprise Linux for x86_64 - Extended Update Support"
    redhat: "True"
    mirroring_policy: "mirror_complete"
    download_policy: "on_demand"
  - name: "Red Hat Enterprise Linux 6 Server - Extended Update Support RPMs x86_64 6.7"
    label: "Red_Hat_Enterprise_Linux_6_Server_-_Extended_Update_Support_RPMs_x86_64_6_7"
    url: "https://cdn.********.com/content/eus/rhel/server/6/6.7/x86_64/os"
    http_proxy_policy: "global_default_http_proxy"
    content_type: "yum"
    product: "Red Hat Enterprise Linux for x86_64 - Extended Update Support"
    redhat: "True"
    mirroring_policy: "mirror_complete"
    download_policy: "on_demand"
