---
repository_sets:
  - label: "satellite-capsule-6.11-for-rhel-8-x86_64-rpms"
  - label: "satellite-client-6-for-rhel-8-x86_64-rpms"
  - label: "satellite-maintenance-6.11-for-rhel-8-x86_64-rpms"
  - label: "rhel-6-server-eus-rpms"
    repositories:
      - releasever: "6.7"
        basearch: "x86_64"
      - releasever: "6.5"
        basearch: "x86_64"
  - label: "satellite-capsule-6.16-for-rhel-8-x86_64-rpms"
  - label: "satellite-maintenance-6.16-for-rhel-8-x86_64-rpms"
  - label: "rhel-ha-for-rhel-7-server-rpms"
    repositories:
      - releasever: "7Server"
        basearch: "x86_64"
  - label: "rhel-8-for-x86_64-baseos-rpms"
    repositories:
      - releasever: "8"
  - label: "rhel-8-for-x86_64-baseos-kickstart"
    repositories:
      - releasever: "8.10"
  - label: "rhel-8-for-x86_64-appstream-rpms"
    repositories:
      - releasever: "8"
  - label: "rhel-8-for-x86_64-appstream-kickstart"
    repositories:
      - releasever: "8.10"
  - label: "rhel-8-for-x86_64-highavailability-rpms"
    repositories:
      - releasever: "8"
