---
repositories:
  - name: "Admin Tools"
    label: "Admin_Tools"
    url: "https://satellite.lab.eiva.com/pulp/content/Primary_Organization/Library/custom/Custom_Software/Admin_Tools/"
    http_proxy_policy: "global_default_http_proxy"
    content_type: "yum"
    product: "Custom Software"
    mirroring_policy: "mirror_content_only"
    download_policy: "immediate"
    gpg_key: "Example Software"
  - name: "Red Hat Enterprise Linux 8 for x86_64 - AppStream Kickstart 8.10"
    label: "Red_Hat_Enterprise_Linux_8_for_x86_64_-_AppStream_Kickstart_8_10"
    url: "https://satellite.lab.eiva.com/pulp/content/Primary_Organization/Library/content/dist/rhel8/8.10/x86_64/appstream/kickstart/"
    http_proxy_policy: "global_default_http_proxy"
    content_type: "yum"
    product: "Red Hat Enterprise Linux for x86_64"
    mirroring_policy: "mirror_complete"
    download_policy: "on_demand"
    gpg_key: ""
  - name: "Red Hat Enterprise Linux 8 for x86_64 - AppStream RPMs 8"
    label: "Red_Hat_Enterprise_Linux_8_for_x86_64_-_AppStream_RPMs_8"
    url: "https://satellite.lab.eiva.com/pulp/content/Primary_Organization/Library/content/dist/rhel8/8/x86_64/appstream/os/"
    http_proxy_policy: "global_default_http_proxy"
    content_type: "yum"
    product: "Red Hat Enterprise Linux for x86_64"
    mirroring_policy: "mirror_complete"
    download_policy: "on_demand"
    gpg_key: ""
  - name: "Red Hat Enterprise Linux 8 for x86_64 - BaseOS Kickstart 8.10"
    label: "Red_Hat_Enterprise_Linux_8_for_x86_64_-_BaseOS_Kickstart_8_10"
    url: "https://satellite.lab.eiva.com/pulp/content/Primary_Organization/Library/content/dist/rhel8/8.10/x86_64/baseos/kickstart/"
    http_proxy_policy: "global_default_http_proxy"
    content_type: "yum"
    product: "Red Hat Enterprise Linux for x86_64"
    mirroring_policy: "mirror_complete"
    download_policy: "on_demand"
    gpg_key: ""
  - name: "Red Hat Enterprise Linux 8 for x86_64 - BaseOS RPMs 8"
    label: "Red_Hat_Enterprise_Linux_8_for_x86_64_-_BaseOS_RPMs_8"
    url: "https://satellite.lab.eiva.com/pulp/content/Primary_Organization/Library/content/dist/rhel8/8/x86_64/baseos/os/"
    http_proxy_policy: "global_default_http_proxy"
    content_type: "yum"
    product: "Red Hat Enterprise Linux for x86_64"
    mirroring_policy: "mirror_complete"
    download_policy: "on_demand"
    gpg_key: ""
  - name: "Red Hat Enterprise Linux 8 for x86_64 - High Availability RPMs 8"
    label: "Red_Hat_Enterprise_Linux_8_for_x86_64_-_High_Availability_RPMs_8"
    url: "https://satellite.lab.eiva.com/pulp/content/Primary_Organization/Library/content/dist/rhel8/8/x86_64/highavailability/os/"
    http_proxy_policy: "global_default_http_proxy"
    content_type: "yum"
    product: "Red Hat Enterprise Linux High Availability for x86_64"
    mirroring_policy: "mirror_complete"
    download_policy: "on_demand"
    gpg_key: ""
  - name: "Red Hat Satellite Capsule 6.11 for RHEL 8 x86_64 RPMs"
    label: "Red_Hat_Satellite_Capsule_6_11_for_RHEL_8_x86_64_RPMs"
    url: "https://satellite.lab.eiva.com/pulp/content/Primary_Organization/Library/content/dist/layered/rhel8/x86_64/sat-capsule/6.11/os/"
    http_proxy_policy: "global_default_http_proxy"
    content_type: "yum"
    product: "Red Hat Satellite Capsule"
    mirroring_policy: "mirror_complete"
    download_policy: "on_demand"
    gpg_key: ""
  - name: "Red Hat Satellite Client 6 for RHEL 8 x86_64 RPMs"
    label: "Red_Hat_Satellite_Client_6_for_RHEL_8_x86_64_RPMs"
    url: "https://satellite.lab.eiva.com/pulp/content/Primary_Organization/Library/content/dist/layered/rhel8/x86_64/sat-client/6/os/"
    http_proxy_policy: "global_default_http_proxy"
    content_type: "yum"
    product: "Red Hat Enterprise Linux for x86_64"
    mirroring_policy: "mirror_complete"
    download_policy: "on_demand"
    gpg_key: ""
  - name: "Red Hat Satellite Maintenance 6.11 for RHEL 8 x86_64 RPMs"
    label: "Red_Hat_Satellite_Maintenance_6_11_for_RHEL_8_x86_64_RPMs"
    url: "https://satellite.lab.eiva.com/pulp/content/Primary_Organization/Library/content/dist/layered/rhel8/x86_64/sat-maintenance/6.11/os/"
    http_proxy_policy: "global_default_http_proxy"
    content_type: "yum"
    product: "Red Hat Enterprise Linux for x86_64"
    mirroring_policy: "mirror_complete"
    download_policy: "on_demand"
    gpg_key: ""
