---
satellite_activation_keys:
  - name: red_ribbonAK
    description: red_ribbonAK description
    unlimited_hosts: True
    auto_attach: True
    organization: red_ribbon
    content_view: cv-test
    lifecycle_environment: UAT
  - name: newAK
    unlimited_hosts: True
    auto_attach: True
    organization: Umbrella
...
