---
satellite_auth_sources_ldap:
  - host: idm.bcnconsulting.com
    port: 389
    attr_login: uid
    attr_firstname: givenName
    attr_lastname: sn
    attr_mail: mail
    attr_photo: jpegPhoto
    onthefly_register: True
    usergroup_sync: True
    tls: False
    server_type: posix
    use_netgroups: False
    type: AuthSourceLdap
    name: idm.bcnconsulting.com
    locations:
      - Barcelona
      - Onda
    organizations:
      - red_ribbon
      - Umbrella
  - host: idm.bcnconsulting.com
    port: 389
    attr_login: uid
    attr_firstname: givenName
    attr_lastname: sn
    attr_mail: mail
    attr_photo: jpegPhoto
    onthefly_register: True
    usergroup_sync: True
    tls: False
    server_type: posix
    use_netgroups: False
    type: AuthSourceLdap
    name: idm.bcnconsulting.com 2
    locations:
      - Onda
    organizations:
      - red_ribbon
  - host: idm.bcnconsulting.com
    port: 389
    attr_login: uid
    attr_firstname: givenName
    attr_lastname: sn
    attr_mail: mail
    attr_photo: jpegPhoto
    onthefly_register: True
    usergroup_sync: True
    tls: False
    server_type: posix
    use_netgroups: False
    type: AuthSourceLdap
    name: idm.bcnconsulting.com 3
    locations:
      - Barcelona
    organizations:
      - Umbrella
...
