---
satellite_sync_plans:
  - name: TestSyncPlan2
    interval: hourly
    next_sync: 2026-01-14 15:33:00 UTC
    sync_date: 2025-12-19 09:33:00 +0000
    enabled: True
    foreman_tasks_recurring_logic_id: 18
    permissions:
      view_sync_plans: True
      edit_sync_plans: True
      destroy_sync_plans: True
    organization: red_ribbon
  - name: TestSyncPlan2
    interval: hourly
    next_sync: 2026-01-14 15:33:00 UTC
    sync_date: 2025-12-19 09:33:00 +0000
    enabled: True
    foreman_tasks_recurring_logic_id: 18
    permissions:
      view_sync_plans: True
      edit_sync_plans: True
      destroy_sync_plans: True
    organization: red_ribbon_new
  - name: TestSyncPlan2
    interval: hourly
    next_sync: 2026-01-14 15:33:00 UTC
    sync_date: 2025-12-19 09:33:00 +0000
    enabled: True
    foreman_tasks_recurring_logic_id: 18
    permissions:
      view_sync_plans: True
      edit_sync_plans: True
      destroy_sync_plans: True
    organization: red_ribbon_new_demo
  - name: TestSyncPlan2
    interval: hourly
    next_sync: 2026-01-14 15:33:00 UTC
    sync_date: 2025-12-19 09:33:00 +0000
    enabled: True
    foreman_tasks_recurring_logic_id: 18
    permissions:
      view_sync_plans: True
      edit_sync_plans: True
      destroy_sync_plans: True
    organization: red_ribbon_new_demo_2
  - name: TestSyncPlan2
    interval: hourly
    next_sync: 2026-01-14 15:33:00 UTC
    sync_date: 2025-12-19 09:33:00 +0000
    enabled: True
    foreman_tasks_recurring_logic_id: 18
    permissions:
      view_sync_plans: True
      edit_sync_plans: True
      destroy_sync_plans: True
    organization: Umbrella
  - name: TestSyncPlan
    interval: custom cron
    next_sync: 2026-01-19 00:00:00 UTC
    sync_date: 2025-12-18 23:00:00 +0000
    enabled: True
    foreman_tasks_recurring_logic_id: 19
    cron_expression: 0 1 1 1 1
    products:
      - Red Hat Enterprise Linux for x86_64
      - Red Hat Ansible Automation Platform
    permissions:
      view_sync_plans: True
      edit_sync_plans: True
      destroy_sync_plans: True
    organization: Umbrella
...
