---
settings:
  - name: foreman_tasks_sync_task_timeout 
    value: 120
  - name: dynflow_enable_console 
    value: True
  - name: dynflow_console_require_auth 
    value: True
  - name: foreman_tasks_proxy_action_retry_count 
    value: 4
  - name: foreman_tasks_proxy_action_retry_interval 
    value: 15
  - name: foreman_tasks_proxy_batch_trigger 
    value: True
  - name: foreman_tasks_proxy_batch_size 
    value: 100
  - name: foreman_tasks_troubleshooting_url 
    value: https://access.********.com/solutions/satellite6-tasks#%{label}
  - name: foreman_tasks_polling_multiplier 
    value: 1
  - name: bootdisk_ipxe_dir 
    value: /usr/share/ipxe
  - name: bootdisk_isolinux_dir 
    value: /usr/share/syslinux
  - name: bootdisk_syslinux_dir 
    value: /usr/share/syslinux
  - name: bootdisk_grub2_dir 
    value: /var/lib/tftpboot/grub2
  - name: bootdisk_host_template 
    value: Boot disk iPXE - host
  - name: bootdisk_generic_host_template 
    value: Boot disk iPXE - generic host
  - name: bootdisk_generic_efi_host_template 
    value: Boot disk Grub2 EFI - generic host
  - name: bootdisk_mkiso_command 
    value: genisoimage
  - name: bootdisk_cache_media 
    value: True
  - name: bootdisk_allowed_types 
    value: ['subnet', 'full_host']
  - name: discovery_location 
    value: 
