---
subnets:
  - name: "Test Subnet 1"
    description: "Test Subnet 1 description"
    network: "192.168.1.0"
    mask: "255.255.255.0"
    gateway: "192.168.1.1"
    network_type: "IPv4"
    organizations:
      - "Operations"
    boot_mode: "DHCP"
    vlanid: 0
    mtu: 1500
    from_ip: "192.168.1.50"
    to_ip: "192.168.1.70"
    ipam: "DHCP"
    remote_execution_proxies:
    locations:
      - "Boston"
      - "Boston/Boston East"
      - "Boston/Boston West"
    domains:
      - "lab.eiva.com"
      - "prod.domain.local"
  - name: "Test Subnet 2"
    description: "Description for Test Subnet 2"
    network: "192.168.2.0"
    mask: "255.255.255.0"
    gateway: "192.168.2.1"
    network_type: "IPv4"
    organizations:
      - "Operations"
      - "Primary Organization"
    dns_primary: ""
    dns_secondary: ""
    boot_mode: "DHCP"
    vlanid: 0
    mtu: 1500
    from_ip: ""
    to_ip: ""
    ipam: "DHCP"
    remote_execution_proxies:
      - "capsule.lab.eiva.com"
      - "satellite.lab.eiva.com"
    locations:
      - "Boston"
      - "Boston/Boston East"
      - "Boston/Boston West"
      - "Default Location"
    domains:
      - "lab.eiva.com"
      - "lab.example.com"
  - name: "Boston Subnet"
    description: "Boston Subnet"
    network: "192.168.122.0"
    mask: "255.255.255.0"
    gateway: "192.168.122.1"
    network_type: "IPv4"
    organizations:
      - "Operations"
      - "Primary Organization"
    dns_primary: "192.168.122.100"
    dns_secondary: "192.168.122.101"
    boot_mode: "DHCP"
    vlanid: 100
    mtu: 1500
    from_ip: "192.168.122.50"
    to_ip: "192.168.122.70"
    ipam: "DHCP"
    remote_execution_proxies:
      - "capsule.lab.eiva.com"
      - "satellite.lab.eiva.com"
    locations:
      - "Boston"
      - "Boston/Boston East"
      - "Boston/Boston West"
      - "Default Location"
    domains:
      - "boston.lab.eiva.com"
