---
satellite_subnets: 
  - network: 10.10.10.0
    network_type: IPv4
    cidr: 27
    mask: 255.255.255.224
    mtu: 1500
    boot_mode: DHCP
    name: test_subnet
    network_address: 10.10.10.0/27
...
