---
# defaults file for dispatch
satellite_username: '{{ lookup("env", "SATELLITE_SERVER_URL") }}'
satellite_password: '{{ lookup("env", "SATELLITE_USERNAME") }}'
satellite_server_url: '{{ lookup("env", "SATELLITE_PASSWORD") }}'
###################
## ContentViews:
###################
content_views_purge_count: 6

