---
- name: Playbook to test the roles 'automationiberia.satellite_configuration'.'filetree_read' and 'dispatch'
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    username: &username "{{ satellite.admin.username }}"
    password: &password "{{ satellite.admin.password }}"
    server_url: &server_url "{{ satellite.server_url }}"
    validate_certs: &validate_certs "{{ satellite.validate_certs }}"
  module_defaults:
    group/redhat.satellite.satellite: &creds
      username: *username
      password: *password
      server_url: *server_url
      validate_certs: *validate_certs
  roles:
    - role: automationiberia.satellite_configuration.filetree_read
    - role: automationiberia.satellite_configuration.dispatch
...
