---
- hosts: localhost
  connection: local
  gather_facts: no
  module_defaults:
    redhat.satellite.organization: &satellite_creds
      username: "{{ satellite.admin.username }}"
      password: "{{ satellite.admin.password }}"
      server_url: "{{ satellite.server_url }}"
      validate_certs: "{{ satellite.validate_certs }}"
    redhat.satellite.activation_key: *satellite_creds
    redhat.satellite.sync_plan: *satellite_creds
  roles:
    - role: automationiberia.satellite_configuration.filetree_read
    - role: automationiberia.satellite_configuration.dispatch
...
